package com.recruitingtransactionos.coreapi.integration;

public enum OutboundIntegrationStatus {
  AUDITED_PROVIDER_ACCEPTED,
  AUDITED_PROVIDER_UNCONFIGURED,
  AUDITED_PROVIDER_PLACEHOLDER,
  AUDITED_PROVIDER_FAILED_CLOSED,
  AUDITED_PROVIDER_REJECTED,
  BLOCKED_CROSS_ORG,
  BLOCKED_SENSITIVE_DATA
}
