package com.recruitingtransactionos.coreapi.integration;

enum IntegrationPayloadKind {
  SAFE_SUMMARY_EXPORT,
  FOLLOW_UP_MESSAGE,
  CALENDAR_INVITE,
  WEBHOOK_EVENT
}

enum RedactionDecision {
  SAFE_SUMMARY_ONLY,
  DISCLOSURE_UNLOCK_CONFIRMED,
  RAW_CANDIDATE_FIELD_BLOCKED
}

enum DisclosureState {
  NOT_DISCLOSED,
  DISCLOSED
}

enum OutboundIntegrationStatus {
  AUDITED_PROVIDER_ACCEPTED,
  AUDITED_PROVIDER_UNCONFIGURED,
  AUDITED_PROVIDER_PLACEHOLDER,
  BLOCKED_CROSS_ORG,
  BLOCKED_SENSITIVE_DATA
}
