package com.recruitingtransactionos.coreapi.truthlayer;

import java.util.Arrays;

public enum WorkflowActionCode {
  CLAIM_LEDGER_ITEM_APPENDED,
  REVIEW_EVENT_APPENDED,
  CANONICAL_WRITE_ATTEMPTED,
  CANONICAL_WRITE_ALLOWED,
  CANONICAL_WRITE_BLOCKED,
  JOB_SUBMITTED,
  JOB_INTAKE_REVIEW_STARTED,
  JOB_MORE_INFO_REQUESTED,
  JOB_COMMERCIAL_PENDING,
  JOB_CONTRACT_PENDING,
  JOB_ACTIVATED,
  JOB_SHORTLIST_IN_PROGRESS,
  JOB_SHORTLIST_SENT,
  JOB_INTERVIEWING,
  JOB_OFFER_PENDING,
  JOB_CLOSED,
  JOB_PAUSED,
  JOB_CANCELLED,
  CANDIDATE_PROFILE_PARSED,
  CANDIDATE_PROFILE_CONFIRMED,
  CANDIDATE_CONSULTANT_REVIEW_STARTED,
  CANDIDATE_MARKED_AVAILABLE,
  CANDIDATE_MATCHED_TO_JOB,
  CANDIDATE_OUTREACH_STARTED,
  CANDIDATE_INTEREST_RECORDED,
  CANDIDATE_CONSENT_PENDING,
  CANDIDATE_CONSENT_CONFIRMED,
  CANDIDATE_FOLLOW_UP_SUBMITTED,
  CANDIDATE_SHORTLISTED,
  CANDIDATE_CLIENT_REVIEW_STARTED,
  CANDIDATE_IDENTITY_DISCLOSED,
  CANDIDATE_INTERVIEWING,
  CANDIDATE_OFFER_PENDING,
  CANDIDATE_PLACED,
  CANDIDATE_REJECTED,
  CANDIDATE_ARCHIVED,
  CANDIDATE_DO_NOT_CONTACT_MARKED,
  SHORTLIST_DRAFT_CREATED,
  SHORTLIST_CARD_REMOVED,
  SHORTLIST_CARD_RESTORED,
  SHORTLIST_RETURNED_TO_DRAFT,
  SHORTLIST_READY_FOR_REVIEW,
  SHORTLIST_SENT_TO_CLIENT,
  SHORTLIST_VIEWED_BY_CLIENT,
  SHORTLIST_CLIENT_FEEDBACK_PENDING,
  SHORTLIST_CANDIDATE_SELECTED,
  SHORTLIST_CONTACT_UNLOCKED,
  SHORTLIST_CLOSED,
  CONSENT_REQUESTED,
  CONSENT_VIEWED_BY_CANDIDATE,
  CONSENT_CONFIRMED,
  CONSENT_DECLINED,
  CONSENT_EXPIRED,
  CONSENT_REVOKED,
  DISCLOSURE_UNLOCK_REQUESTED,
  DISCLOSURE_UNLOCK_APPROVED,
  DISCLOSURE_UNLOCK_REJECTED,
  DISCLOSURE_CONSULTANT_APPROVED,
  DISCLOSURE_IDENTITY_DISCLOSED,
  DISCLOSURE_FEE_PROTECTION_ACTIVATED,
  PRIOR_CONTACT_CLAIM_CREATED,
  PRIOR_APPLICATION_CLAIM_CREATED,
  SOURCE_ITEM_REGISTERED,
  INFORMATION_PACKET_CREATED,
  PLACEMENT_RECORDED,
  OFFER_ACCEPTED,
  CANDIDATE_ONBOARDED,
  INVOICE_READY,
  INVOICE_SENT,
  PAYMENT_MARKED_PAID,
  GUARANTEE_ACTIVATED,
  GUARANTEE_COMPLETED,
  REPLACEMENT_REQUIRED,
  COMMISSION_PENDING,
  COMMISSION_PAID,
  COMMISSION_WITHHELD,
  AI_TASK_RUN_RECORDED,
  AI_RECOMMENDATION_RECORDED,
  REIDENTIFICATION_RISK_ASSESSED,
  CLIENT_SAFE_REDACTION_BLOCKED,
  CLIENT_CLARIFICATION_REQUESTED,
  CLIENT_CLARIFICATION_ANSWERED,
  NOTIFICATION_REMINDER_TRIGGERED,
  DATA_DUPLICATE_BLOCKED,
  DATA_DUPLICATE_WARNING_RECORDED,
  DATA_MERGE_PROPOSED,
  DATA_MERGE_BLOCKED_CONFIRMED_FACT_CONFLICT,
  DATA_CONFLICT_RESOLUTION_RECORDED,
  DATA_REFRESH_REQUESTED,
  DATA_RETENTION_DELETION_BLOCKED,
  DATA_RETENTION_DELETION_EXECUTED;

  public String wireValue() {
    return name();
  }

  public static WorkflowActionCode fromWireValue(String value) {
    if (value == null) {
      throw new NullPointerException("action code must not be null");
    }
    if (value.isBlank()) {
      throw new IllegalArgumentException("action code must not be blank");
    }
    return Arrays.stream(values())
        .filter(actionCode -> actionCode.wireValue().equals(value))
        .findFirst()
        .orElseThrow(() -> new IllegalArgumentException(
            "unknown workflow action code: " + value));
  }
}
