package com.recruitingtransactionos.coreapi.apiboundary;

public sealed interface ApiSafeResponseBody
    permits ApiErrorResponse,
        ApiAccessDeniedResponse,
        ApiValidationErrorResponse,
        AuthSessionResponse,
        AuthLogoutResponse,
        ClientSafeCandidateCardResponse,
        ConsultantCandidateSummaryResponse,
        ConsultantCandidateDetailResponse,
        ConsultantDashboardResponse,
        ConsultantWorkflowEntityStateResponse,
        ConsultantWorkflowTimelineResponse,
        ConsultantAuditDrawerResponse,
        ConsultantBlockedActionResponse,
        ConsultantWorkflowEventResponse,
        ConsultantFollowUpSummaryResponse,
        ConsultantCompanySummaryResponse,
        ConsultantMatchReportResponse,
        ConsultantMatchReportListResponse,
        ConsultantCompanyDetailResponse,
        ConsultantJobSummaryResponse,
        ConsultantJobDetailResponse,
        ConsultantJobActivationGateResponse,
        ConsultantShortlistSummaryResponse,
        ConsultantShortlistDetailResponse,
        ClientCompanyProfileResponse,
        ClientJobSubmissionStatusResponse,
        ClientPreferenceResponse,
        ClientShortlistSummaryResponse,
        ClientShortlistDetailResponse,
        ClientShortlistCandidateSelectionResponse,
        ClientUnlockRequestResponse,
        ClientDisclosedCandidateResponse,
        ClientInterviewFeedbackResponse,
        ClientDashboardResponse,
        CandidateConsentSummaryResponse,
        CandidateFollowUpFormResponse,
        CandidateMeResponse,
        CandidateOpportunityDetailResponse,
        CandidateProfileReviewResponse,
        CandidateDocumentSummaryResponse,
        CandidateOpportunityResponse,
        CandidateTimelineResponse,
        ConsultantUnlockQueueResponse,
        ConsultantUnlockDecisionResponse,
        ConsultantDocumentUploadResponse,
        ConsultantParsedDocumentResponse,
        ConsultantDocumentEvidenceResponse,
        ConsultantIntakeRunResponse,
        ConsultantIntakeQueueResponse,
        ConsultantIntakeReviewResponse,
        ConsultantIntakePublishResponse,
        PagedResult {}
