package com.recruitingtransactionos.coreapi.apiboundary;

public sealed interface ApiSafeResponseBody
    permits ApiErrorResponse,
        ApiAccessDeniedResponse,
        ApiValidationErrorResponse,
        AuthSessionResponse,
        AuthLogoutResponse,
        ClientSafeCandidateCardResponse,
        ConsultantCandidateSummaryResponse,
        ConsultantCandidateDetailResponse,
        ConsultantDashboardResponse,
        ConsultantWorkflowTimelineResponse,
        ConsultantAuditDrawerResponse,
        ConsultantBlockedActionResponse,
        ConsultantWorkflowEventResponse,
        ConsultantFollowUpSummaryResponse,
        ConsultantCompanySummaryResponse,
        ConsultantMatchReportResponse,
    ConsultantCompanyDetailResponse,
        ConsultantJobSummaryResponse,
        ConsultantJobDetailResponse,
        ConsultantShortlistSummaryResponse,
        ConsultantShortlistDetailResponse,
        ConsultantDocumentUploadResponse,
        ConsultantParsedDocumentResponse,
        ConsultantDocumentEvidenceResponse,
        ConsultantIntakeRunResponse,
        ConsultantIntakeQueueResponse,
        ConsultantIntakeReviewResponse,
        ConsultantIntakePublishResponse,
        PagedResult {}
